config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show]

  resources :lists do
    resources :items, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :lists, except: [:show] do
        resources :items, only: [:create, :destroy]
      end
    end
  end

  root to: 'welcome#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  default_scope { order('created_at DESC') }

  def days_left
    7 - ((DateTime.now.to_date - created_at.to_date).to_i)
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
  validates :api_key, uniqueness: true
  before_create :assign_key

  def assign_key
    self.api_key = self.generate_api_key
  end

  def admin?
    role == 'admin'
  end

  def generate_api_key
    loop do
      token = SecureRandom.base64.tr('+/=', 'Qrt')
      break token unless User.exists?(api_key: token)
    end
  end

end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  
  before_action :authenticate

  private

  def current_user
    @user
  end

  def authenticate
    api_key = request.headers['X-Api-Key']
    @user = User.where(api_key: api_key).first if api_key
   
    unless @user
      head status: :unauthorized
      return false
    end
  end
end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < Api::ApiController
  respond_to :json

  def create

    @list = current_user.lists.find(params[:list_id])
    @items = @list.items
    @item = @list.items.build(item_params)
    @item.list = @list

    if @item.save
      render json: @item
    end
  end

  def destroy
    @list = current_user.lists.find(params[:list_id])
    @item = @list.items.find(params[:id])
    respond_with @item.destroy
  end

  private
  def item_params
    params.require(:item).permit(:name)
  end

end

app/controllers/api/v1/lists_controller.rb
class Api::V1::ListsController < Api::ApiController
  respond_to :json

  def index
    render json: @user.lists
  end

  def new
    @list = List.new
  end

  def create
    @list = @user.lists.new(list_params)
    if @list.save
      render json: @list
    end
  end

  def update
    respond_with current_user.lists.find(params[:id]).update_attributes(list_params)
  end

  def destroy
    respond_with current_user.lists.destroy(params[:id])
  end

  private
  def list_params
    params.require(:list).permit(:title)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :js

  def create
    @list = List.find(params[:list_id])
    @items = @list.items

    @item = @list.items.build(item_params)
    @item.list = @list
    @new_item = Item.new

    if @item.save
      flash[:notice] = "Item was saved."
    else
      flash[:error] = "There was an error saving the item. Please try again."
    end

    respond_with(@item) do |format|
      format.html { redirect_to [@list] }
    end

  end

  def destroy
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item was deleted."
    else
      flash[:error] = "Error deleting item. Please try again."
    end

    respond_with(@item) do |format|
      format.html { redirect_to [@list] }
    end

  end

  private

  def item_params
    params.require(:item).permit(:name)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @list = @user.lists.find(params[:id])
    @items = @list.items.order(created_at: :desc)
    authorize @list
  end

  def index
    @lists = current_user.lists
    authorize @lists
  end

  def new
    @user = current_user
    @list = @user.lists.new
    authorize @list
  end

  def edit
    @list = List.find(params[:id])
    authorize @list
  end

  def create
    @list = current_user.lists.build(list_params)
    authorize @list

    if @list.save
      flash[:notice] = "List was saved."
      redirect_to lists_path
    else
      flash[:error] = "There was an error saving the list. Please try again."
      render :new
    end
  end

  def update
    @list = current_user.lists.find(params[:id])

    if @list.update_attributes(list_params)
      flash[:notice] = "List was updated."
      redirect_to lists_path
    else
      flash[:error] = "There was an error updating the list. Please try again."
      render :edit
    end
  end

  def destroy
    @list = current_user.lists.find(params[:id])
    title = @list.title

    if @list.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @list
    else
      flash[:error] = "There was an error deleting the list. Please try again."
      render :show
    end
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @lists = @user.lists
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<div class="col-lg-10 col-lg-offset-1">
  <%= simple_form_for [@list, @list.items.build], html: { class: 'inline-form' }, remote: true, format: :js do |f| %>
    <div class="input-group">
        <%= f.input :name, label: false, placeholder: "Add a New Item", class: "form-control", as: :string %>
      <span class="input-group-btn">
        <%= button_tag(type: 'submit', class: "btn btn-success") do %>
          <i class="fa fa-plus"></i> Add
        <% end %>
      </span>
    </div>
  <% end %>
</div>

app/views/items/_item.html.erb
<tr>
  <td><%= item.name %></td>
  <td><%= item.days_left %></td>
  <td><%= link_to "Delete", [item.list, item], class: 'fa fa-trash-o', method: :delete, remote: true %></td>
</tr>

app/views/items/create.js.erb
<% if @item.valid? %>
  $('tbody').prepend("<%= escape_javascript(render(@item)) %>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { list: @item.list, item: @new_item }) %>");
<% else %>
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { list: @item.list, item: @item }) %>");
<% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-<%= @item.id %>').fadeOut( "slow" );
<% else %>
  $('#item-<%= @item.id %>').prepend("<div class='alert alert-danger'><%= flash.discard(:error) %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/navbar' %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/lists/_list.html.erb
<%= link_to list.title, list_path(list) %><br>

app/views/lists/edit.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :title, label: 'Title', placeholder: "Enter list title" %>
  <%= f.submit 'Save' , class: 'btn btn-success' %>
<% end %>

app/views/lists/index.html.erb
<%= render @lists %>

<%= link_to "New To-do List", new_list_path, class: 'btn btn-success' %>   

app/views/lists/new.html.erb
<%= simple_form_for @user.lists.new ,:url => {:action => :create, :controller => :lists} do |f| %>
  <%= f.input :title, label: 'Title', placeholder: "Enter list title" %>
  <%= f.submit 'Save' , class: 'btn btn-success' %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <%= link_to '<-- Back', lists_path %>
      <h1><%= @list.title %></h1>
    </div>
  </div>
  <div class="row">
    <div class="new-item">
      <%= render partial: 'items/form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <table class="table table-striped">
        <thead>
          <tr>
            <th data-field="Description">Description</th>
            <th data-field="Days Left">Days Left</th>
            <th data-field="Delete">Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr id="item-<%= item.id %>">
              <td><%= item.name %></td>
              <td><%= item.days_left %></td>
              <td><%= link_to "Delete", [item.list, item],class: 'fa fa-trash-o', method: :delete, remote: true %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Blocitoff</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'btn btn-danger' %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, :class => 'btn btn-default' %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-default' %>
        <% end %>
      </ul>


    </div>
  </div>
</nav>

app/views/users/show.html.erb
<% if @user == current_user %>
  <h2>User Information</h2>
  <%= "Current User: #{ @user.email }" %>
  <br>
  <%= "API Key: #{ @user.api_key }" %>
  <h3>Lists</h3>
  <% @lists.each do |list| %>
        <div id="list-<%= list.id %>">
          <%= link_to list.title, list_path(list) %>
        </div>
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <h1>Blocitoff:</h1>
      <p>A self-destructing to-do list to keep you focused on the things that really matter.</p>
    </div>
  </div>
<div>